# Generated by Django 6.0.2 on 2026-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('report_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=100)),
                ('reporter', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=20)),
                ('image_res_id', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reporter_mobile', models.CharField(max_length=20)),
                ('reporter_email', models.CharField(default='unknown@link.com', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('CITIZEN', 'Citizen'), ('AUTHORITY', 'Authority')], max_length=20)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
