# Generated by Django 6.0.2 on 2026-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='supervisor_image',
            field=models.ImageField(blank=True, null=True, upload_to='supervisor_evidence/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='supervisor_image_res_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('AUTHORITY', 'Authority'), ('SUPERVISOR', 'Supervisor')], max_length=20),
        ),
    ]
