# Generated by Django 6.0.2 on 2026-03-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_complaint_supervisor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proof_evidence/'),
        ),
    ]
