# Generated by Django 6.0.2 on 2026-03-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_complaint_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='supervisor_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
