# Generated by Django 6.0.2 on 2026-03-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_complaint_supervisor_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='authority_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rating_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
